controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    joints:
      - finger_1_joint_1
      - finger_1_joint_2
      - finger_1_joint_3
      - finger_2_joint_2
      - finger_2_joint_3
      - finger_middle_joint_1
      - finger_middle_joint_2
      - finger_middle_joint_3
  - name: fake_end_effector_controller
    joints:
      []